# Simple XOR example 
This example is part of Siraj's video in *Neural Network* section,* Lesson 1*. It's a short [video](https://www.youtube.com/watch?v=N4gDikiec8E) and he quickly explains how this stuff works. 
[This Github rpeo](https://github.com/llSourcell/how_to_do_math_for_deep_learning/blob/master/demo.ipynb) contains the code and jupyter notebook


In [25]:
import numpy as np

In [26]:
#Step 1: collect data. Last input is the bias 
x = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
y = np.array([0,1,1,0]).reshape(4,1)

In [27]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [28]:
print(y)

[[0]
 [1]
 [1]
 [0]]


In [29]:
# Step 2: Build the model

num_epochs = 60000

# initialize weights to random values between -1 and 1
"""
What we need is to have 3 input, forward propagated to 4 neurons, 
then it gives just 1 output
"""
syn0 = 2 * np.random.random((3,4)) - 1
syn1 = 2 * np.random.random((4,1)) - 1

In [30]:
def nonlin(x, deriv=False):
    if deriv == True: return x * (1-x)
    return 1/(1+np.exp(-x))

In [31]:
# Step 3: Train model
for j in range(num_epochs):
    k0 = x
    k1 = nonlin(np.dot(k0, syn0))
    k2 = nonlin(np.dot(k1, syn1))
    
    k2_error = y - k2
    
    if j % 10000 == 0:
        print('Error: ' + str(np.mean(np.abs(k2_error))))
        
    k2_delta = k2_error * nonlin(k2, deriv=True)
    
    k1_error = k2_delta.dot(syn1.T)
    
    k1_delta = k1_error * nonlin(k1, deriv=True)
    
    syn1 += k1.T.dot(k2_delta)
    syn0 += k0.T.dot(k1_delta)
    

Error: 0.501143956957
Error: 0.0109026600577
Error: 0.00720089018186
Error: 0.00568509353791
Error: 0.00481989312171
Error: 0.00424654611513
